#测试环境###########################################################################################################################################
spring:
  application:
    name: fa-admin-test
  config:
    activate:
      on-profile: test

  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:faber_admin}?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:123456}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ~

server:
  port: 8580

#============================================================================
# netty socket io setting
#============================================================================
# host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
socketio:
  host: 127.0.0.1
  port: 8581

fa:
  setting:
    file:
      # 系统文件存储方式: local-本地存储/qiniu-七牛云
      saveType: local
      # 这里是增加一层路径，用于区分
      prefix: test
