# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 7777

# mysql
spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:faber-admin}?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

